<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-XForms-929f5ff9-26d6-42f7-9905-b2977194df97</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.*" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.*" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.4" />
    <PackageReference Include="Microsoft.Graph" Version="5.77.0" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.22.0" />
    <PackageReference Include="MudBlazor" Version="8.*" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" Version="3.*" />
    <PackageReference Include="MudBlazor.Markdown" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.7" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="Components\Account\Pages\RegisterConfirmation.razor">
      <DependentUpon>LoginWith2fa.razor</DependentUpon>
    </Content>
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Update="Resources\Components\Pages\Home.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Components\Pages\Home.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Home.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <Compile Update="Resources\Components\Pages\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Components\Pages\Home.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Home.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>